### ISSUE TITLE
Question About Data Processing for KPIs Task2

### ISSUE THREAD

**Issue by DigitalImageProcessor** [huuquan1994/wsi_glomerulus_seg#1]
Dear Author,
I hope this message finds you well.
I couldn’t find the data processing part for KPIs Task2 in your GitHub repository or Docker image. The large size of the pathology images in Task2 makes it challenging to process and train the model directly. I was wondering if you could kindly share your approach to handling these images. It would be greatly appreciated if you could provide any references or related code as well.
Thank you for your time and support!

**Comment by huuquan1994** [comment]
@DigitalImageProcessor 
Thanks for your question!
If you visually check the WSIs of the KPIs data, you'll see that they have already been nicely pre-processed with the non-tissue areas removed. Therefore, no need to pre-process these WSIs for KPIs. Note that you might need to pre-process the WSIs for other datasets. 

For your second question, training WSIs directly is not feasible, so we normally train a model (e.g., segmentation model) using the cropped patch images (as provided in Task 1 data of the KPIs challenge).

Please see a plotted WSI of KPIs below
<img width="560" alt="image" src="https://github.com/user-attachments/assets/36c46718-eeda-4330-88d2-2d6c7ef473de">
